config/routes.rb
Rails.application.routes.draw do
  resources :comments

  get 'home/index'

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    def change
    create_table :comment do |t|
      t.string :title
      t.text :text

      t.timestamps
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
  
  def create
    @comment = Comment.new(comment_params)
   
    @comment.save
    redirect_to @comment
  end
   
  def comment_params
    params.require(:comment).permit(:title, :text)
  end
    
  def show
    @comment = Comment.find(params[:id])
  end
  
  def index
    @comment = Comment.all
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/index.html.erb
<h1>Comment List</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @comment.each do |comment| %>
    <tr>
      <td><%= comment.title %></td>
      <td><%= comment.text %></td>
    </tr>
  <% end %>
</table>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= form_for :comment, url: comments_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

app/views/home/index.html.erb
<h1>Welcome to SF</h1>
<p><%= link_to 'Comments', controller: 'comments' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appsf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>